const getEnv = (key: string, value: string | undefined): string => {
  if (!value) {
    throw new Error(`Missing environment variable: ${key}`);
  }
  return value;
};

export const APPWRITE_CONFIG = {
  ENDPOINT: getEnv("NEXT_PUBLIC_APPWRITE_ENDPOINT", process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT),
  PROJECT_ID: getEnv("NEXT_PUBLIC_APPWRITE_PROJECT_ID", process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID),
  DATABASE_ID: getEnv("NEXT_PUBLIC_APPWRITE_DATABASE_ID", process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID),
  TABLES: {
    CALENDARS: getEnv("NEXT_PUBLIC_APPWRITE_TABLE_CALENDARS", process.env.NEXT_PUBLIC_APPWRITE_TABLE_CALENDARS),
    TASKS: getEnv("NEXT_PUBLIC_APPWRITE_TABLE_TASKS", process.env.NEXT_PUBLIC_APPWRITE_TABLE_TASKS),
    EVENTS: getEnv("NEXT_PUBLIC_APPWRITE_TABLE_EVENTS", process.env.NEXT_PUBLIC_APPWRITE_TABLE_EVENTS),
    EVENT_GUESTS: getEnv("NEXT_PUBLIC_APPWRITE_TABLE_EVENT_GUESTS", process.env.NEXT_PUBLIC_APPWRITE_TABLE_EVENT_GUESTS),
    FOCUS_SESSIONS: getEnv("NEXT_PUBLIC_APPWRITE_TABLE_FOCUS_SESSIONS", process.env.NEXT_PUBLIC_APPWRITE_TABLE_FOCUS_SESSIONS),
  },
  BUCKETS: {
    TASK_ATTACHMENTS: getEnv("NEXT_PUBLIC_APPWRITE_BUCKET_TASK_ATTACHMENTS", process.env.NEXT_PUBLIC_APPWRITE_BUCKET_TASK_ATTACHMENTS),
    EVENT_COVERS: getEnv("NEXT_PUBLIC_APPWRITE_BUCKET_EVENT_COVERS", process.env.NEXT_PUBLIC_APPWRITE_BUCKET_EVENT_COVERS),
  },
};
